// Package showtime provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package showtime

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ShowtimeStatus.
const (
	CANCELLED ShowtimeStatus = "CANCELLED"
	SCHEDULED ShowtimeStatus = "SCHEDULED"
)

// Valid indicates whether the value is a known member of the ShowtimeStatus enum.
func (e ShowtimeStatus) Valid() bool {
	switch e {
	case CANCELLED:
		return true
	case SCHEDULED:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Showtime defines model for Showtime.
type Showtime struct {
	CinemaId   int64          `json:"cinema_id"`
	CinemaName string         `json:"cinema_name"`
	EndAt      time.Time      `json:"end_at"`
	Id         int64          `json:"id"`
	MovieId    int64          `json:"movie_id"`
	MovieTitle string         `json:"movie_title"`
	Price      int64          `json:"price"`
	StartAt    time.Time      `json:"start_at"`
	Status     ShowtimeStatus `json:"status"`
	StudioId   int64          `json:"studio_id"`
	StudioName string         `json:"studio_name"`
}

// ShowtimeStatus defines model for Showtime.Status.
type ShowtimeStatus string

// ShowtimeList defines model for ShowtimeList.
type ShowtimeList struct {
	Data  []Showtime `json:"data"`
	Limit int        `json:"limit"`
	Page  int        `json:"page"`
	Total int64      `json:"total"`
}

// ShowtimeRequest defines model for ShowtimeRequest.
type ShowtimeRequest struct {
	MovieId int64 `json:"movie_id"`

	// Price Rupiah, greater than 0.
	Price    int64     `json:"price"`
	StartAt  time.Time `json:"start_at"`
	StudioId int64     `json:"studio_id"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListShowtimesParams defines parameters for ListShowtimes.
type ListShowtimesParams struct {
	MovieId  *int64 `form:"movie_id,omitempty" json:"movie_id,omitempty"`
	CinemaId *int64 `form:"cinema_id,omitempty" json:"cinema_id,omitempty"`

	// From Only showtimes starting at or after this time (RFC 3339). Encode "+" as %2B, e.g. 2026-01-01T00:00:00%2B07:00.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Only showtimes starting before this time (RFC 3339). Encode "+" as %2B.
	To    *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Page  *int       `form:"page,omitempty" json:"page,omitempty"`
	Limit *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateShowtimeJSONRequestBody defines body for CreateShowtime for application/json ContentType.
type CreateShowtimeJSONRequestBody = ShowtimeRequest

// UpdateShowtimeJSONRequestBody defines body for UpdateShowtime for application/json ContentType.
type UpdateShowtimeJSONRequestBody = ShowtimeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List showtimes
	// (GET /api/v1/showtimes)
	ListShowtimes(c *gin.Context, params ListShowtimesParams)
	// Create a showtime (admin)
	// (POST /api/v1/showtimes)
	CreateShowtime(c *gin.Context)
	// Delete a showtime (admin)
	// (DELETE /api/v1/showtimes/{id})
	DeleteShowtime(c *gin.Context, id int64)
	// Get a showtime
	// (GET /api/v1/showtimes/{id})
	GetShowtime(c *gin.Context, id int64)
	// Update a showtime (admin)
	// (PUT /api/v1/showtimes/{id})
	UpdateShowtime(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListShowtimes operation middleware
func (siw *ServerInterfaceWrapper) ListShowtimes(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListShowtimesParams

	// ------------- Optional query parameter "movie_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "movie_id", c.Request.URL.Query(), &params.MovieId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter movie_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cinema_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cinema_id", c.Request.URL.Query(), &params.CinemaId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cinema_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListShowtimes(c, params)
}

// CreateShowtime operation middleware
func (siw *ServerInterfaceWrapper) CreateShowtime(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateShowtime(c)
}

// DeleteShowtime operation middleware
func (siw *ServerInterfaceWrapper) DeleteShowtime(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteShowtime(c, id)
}

// GetShowtime operation middleware
func (siw *ServerInterfaceWrapper) GetShowtime(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetShowtime(c, id)
}

// UpdateShowtime operation middleware
func (siw *ServerInterfaceWrapper) UpdateShowtime(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateShowtime(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/showtimes", wrapper.ListShowtimes)
	router.POST(options.BaseURL+"/api/v1/showtimes", wrapper.CreateShowtime)
	router.DELETE(options.BaseURL+"/api/v1/showtimes/:id", wrapper.DeleteShowtime)
	router.GET(options.BaseURL+"/api/v1/showtimes/:id", wrapper.GetShowtime)
	router.PUT(options.BaseURL+"/api/v1/showtimes/:id", wrapper.UpdateShowtime)
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListShowtimesRequestObject struct {
	Params ListShowtimesParams
}

type ListShowtimesResponseObject interface {
	VisitListShowtimesResponse(w http.ResponseWriter) error
}

type ListShowtimes200JSONResponse ShowtimeList

func (response ListShowtimes200JSONResponse) VisitListShowtimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListShowtimes400JSONResponse struct{ BadRequestJSONResponse }

func (response ListShowtimes400JSONResponse) VisitListShowtimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListShowtimes401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListShowtimes401JSONResponse) VisitListShowtimesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShowtimeRequestObject struct {
	Body *CreateShowtimeJSONRequestBody
}

type CreateShowtimeResponseObject interface {
	VisitCreateShowtimeResponse(w http.ResponseWriter) error
}

type CreateShowtime201JSONResponse Showtime

func (response CreateShowtime201JSONResponse) VisitCreateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShowtime400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShowtime400JSONResponse) VisitCreateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShowtime401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShowtime401JSONResponse) VisitCreateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShowtime403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateShowtime403JSONResponse) VisitCreateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShowtime409JSONResponse struct{ ConflictJSONResponse }

func (response CreateShowtime409JSONResponse) VisitCreateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShowtimeRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteShowtimeResponseObject interface {
	VisitDeleteShowtimeResponse(w http.ResponseWriter) error
}

type DeleteShowtime204Response struct {
}

func (response DeleteShowtime204Response) VisitDeleteShowtimeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteShowtime401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteShowtime401JSONResponse) VisitDeleteShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShowtime403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteShowtime403JSONResponse) VisitDeleteShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShowtime404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteShowtime404JSONResponse) VisitDeleteShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShowtime409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteShowtime409JSONResponse) VisitDeleteShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetShowtimeRequestObject struct {
	Id int64 `json:"id"`
}

type GetShowtimeResponseObject interface {
	VisitGetShowtimeResponse(w http.ResponseWriter) error
}

type GetShowtime200JSONResponse Showtime

func (response GetShowtime200JSONResponse) VisitGetShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetShowtime401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetShowtime401JSONResponse) VisitGetShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetShowtime404JSONResponse struct{ NotFoundJSONResponse }

func (response GetShowtime404JSONResponse) VisitGetShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateShowtimeRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateShowtimeJSONRequestBody
}

type UpdateShowtimeResponseObject interface {
	VisitUpdateShowtimeResponse(w http.ResponseWriter) error
}

type UpdateShowtime200JSONResponse Showtime

func (response UpdateShowtime200JSONResponse) VisitUpdateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateShowtime400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateShowtime400JSONResponse) VisitUpdateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateShowtime401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateShowtime401JSONResponse) VisitUpdateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateShowtime403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateShowtime403JSONResponse) VisitUpdateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateShowtime404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateShowtime404JSONResponse) VisitUpdateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateShowtime409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateShowtime409JSONResponse) VisitUpdateShowtimeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List showtimes
	// (GET /api/v1/showtimes)
	ListShowtimes(ctx context.Context, request ListShowtimesRequestObject) (ListShowtimesResponseObject, error)
	// Create a showtime (admin)
	// (POST /api/v1/showtimes)
	CreateShowtime(ctx context.Context, request CreateShowtimeRequestObject) (CreateShowtimeResponseObject, error)
	// Delete a showtime (admin)
	// (DELETE /api/v1/showtimes/{id})
	DeleteShowtime(ctx context.Context, request DeleteShowtimeRequestObject) (DeleteShowtimeResponseObject, error)
	// Get a showtime
	// (GET /api/v1/showtimes/{id})
	GetShowtime(ctx context.Context, request GetShowtimeRequestObject) (GetShowtimeResponseObject, error)
	// Update a showtime (admin)
	// (PUT /api/v1/showtimes/{id})
	UpdateShowtime(ctx context.Context, request UpdateShowtimeRequestObject) (UpdateShowtimeResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListShowtimes operation middleware
func (sh *strictHandler) ListShowtimes(ctx *gin.Context, params ListShowtimesParams) {
	var request ListShowtimesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListShowtimes(ctx, request.(ListShowtimesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListShowtimes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListShowtimesResponseObject); ok {
		if err := validResponse.VisitListShowtimesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShowtime operation middleware
func (sh *strictHandler) CreateShowtime(ctx *gin.Context) {
	var request CreateShowtimeRequestObject

	var body CreateShowtimeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShowtime(ctx, request.(CreateShowtimeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShowtime")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateShowtimeResponseObject); ok {
		if err := validResponse.VisitCreateShowtimeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteShowtime operation middleware
func (sh *strictHandler) DeleteShowtime(ctx *gin.Context, id int64) {
	var request DeleteShowtimeRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteShowtime(ctx, request.(DeleteShowtimeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteShowtime")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteShowtimeResponseObject); ok {
		if err := validResponse.VisitDeleteShowtimeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShowtime operation middleware
func (sh *strictHandler) GetShowtime(ctx *gin.Context, id int64) {
	var request GetShowtimeRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetShowtime(ctx, request.(GetShowtimeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShowtime")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetShowtimeResponseObject); ok {
		if err := validResponse.VisitGetShowtimeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateShowtime operation middleware
func (sh *strictHandler) UpdateShowtime(ctx *gin.Context, id int64) {
	var request UpdateShowtimeRequestObject

	request.Id = id

	var body UpdateShowtimeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateShowtime(ctx, request.(UpdateShowtimeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateShowtime")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateShowtimeResponseObject); ok {
		if err := validResponse.VisitUpdateShowtimeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
